require('dotenv').config();

const express = require('express');
const cors = require('cors');
const bodyParser = require('body-parser');
const pool = require('./config/db');
const axios = require('axios');
const nodemailer = require('nodemailer');
const path = require('path');

const app = express();
const PORT = Number(process.env.PORT || 3000);
app.use(cors());
app.use(bodyParser.json({ limit: '1mb' }));
app.use(express.static(path.join(__dirname, '../frontend')));

const PIPELINE = ['Applied','Screening','Interview','Offer','Hired','Onboarding','Completed'];
const ALLOWED_STAGES = new Set([...PIPELINE, 'Rejected']);
const clean = v => typeof v === 'string' ? v.trim() : v;
const num = v => v == null || v === '' ? null : Number(v);
function newLookupCode(){return `QM-${Date.now().toString(36).toUpperCase()}-${Math.floor(100+Math.random()*900)}`;}
function canTransition(from,to){
  if(!ALLOWED_STAGES.has(to)) return false;
  if(from===to) return true;
  if(from==='Rejected'||from==='Completed') return false;
  if(to==='Rejected') return true;
  return (from==='Applied'&&to==='Screening')||(from==='Screening'&&to==='Interview')||(from==='Interview'&&to==='Offer')||(from==='Offer'&&to==='Hired')||(from==='Hired'&&to==='Onboarding')||(from==='Onboarding'&&to==='Completed');
}
async function recordStage(c,id,from,to,reason,by='System-Auto'){
  if(from===to) return;
  const exists=await c.query(`SELECT id FROM stage_history WHERE application_id=$1 AND stage_name=$2 AND previous_stage IS NOT DISTINCT FROM $3 AND status='Completed' AND reason IS NOT DISTINCT FROM $4 AND created_at >= NOW()-INTERVAL '2 seconds' LIMIT 1`,[id,to,from||null,reason||null]);
  if(!exists.rows.length) await c.query(`INSERT INTO stage_history(application_id,stage_name,status,previous_stage,triggered_by,reason,completed_at) VALUES($1,$2,'Completed',$3,$4,$5,NOW())`,[id,to,from||null,by,reason||null]);
  await c.query(`UPDATE applications SET progress_log=COALESCE(progress_log,'[]'::jsonb)||jsonb_build_object('stage',$1::text,'from',$2::text,'at',NOW(),'reason',$3::text) WHERE id=$4`,[to,from||null,reason||null,id]);
}
async function transition(c,id,to,reason,by='System-Auto'){
  const r=await c.query('SELECT current_stage FROM applications WHERE id=$1 FOR UPDATE',[id]);
  if(!r.rows.length) return {error:'not_found'};
  const from=r.rows[0].current_stage||'Applied';
  if(!canTransition(from,to)) return {error:'invalid_transition',previousStage:from};
  if(from!==to){await c.query('UPDATE applications SET current_stage=$1 WHERE id=$2',[to,id]);await recordStage(c,id,from,to,reason,by);}
  return {previousStage:from,nextStage:to};
}
async function ensureOnboardingCosts(c,id){
  const r=await c.query('SELECT 1 FROM onboarding_costs WHERE application_id=$1 LIMIT 1',[id]);
  if(r.rows.length) return;
  await c.query(`INSERT INTO onboarding_costs(application_id,cost_item,item_name,estimated_cost,is_required,payment_status) VALUES($1,'Uniform Package','Uniform Package',2500,true,'Unpaid'),($1,'Medical & Food Handler Certificate','Medical & Food Handler Certificate',1000,true,'Unpaid'),($1,'ID Card','ID Card',500,false,'Unpaid')`,[id]);
}
function nextStep(stage){return {Applied:'Screening review',Screening:'Interview review',Interview:'HR interview decision',Offer:'Accept offer and proceed to onboarding',Hired:'Begin onboarding',Onboarding:'Complete onboarding and required payments',Completed:'Process completed',Rejected:'No further action is required'}[stage]||'Check application status';}
function screeningQuestions(){return [
  {id:'availability',question:'Are you available to work the required shifts, including weekends where applicable?',type:'textarea',required:true},
  {id:'experience',question:'Briefly describe your relevant work or customer-service experience.',type:'textarea',required:true},
  {id:'motivation',question:'Why do you want to work with QuickMart?',type:'textarea',required:true}
];}
async function sendCommunication(applicationId,channel,subject,body,recipient){
  let status='Sent';
  try{
    if(channel==='Email'&&process.env.GMAIL_USER&&process.env.GMAIL_APP_PASSWORD){
      const transporter=nodemailer.createTransport({service:'gmail',auth:{user:process.env.GMAIL_USER,pass:process.env.GMAIL_APP_PASSWORD}});
      await transporter.sendMail({from:process.env.GMAIL_USER,to:recipient,subject:subject||'',text:body});
    }
  }catch(e){status='Failed';console.error('Communication send failed:',e.message);}
  const r=await pool.query(`INSERT INTO communications(application_id,channel,direction,subject,body,recipient,status) VALUES($1,$2,'OUT',$3,$4,$5,$6) RETURNING *`,[applicationId,channel,subject||null,body||null,recipient||null,status]);
  return r.rows[0];
}

app.get('/api/jobs',async(req,res)=>{try{res.json((await pool.query("SELECT * FROM jobs WHERE status='Open' ORDER BY posted_date DESC")).rows);}catch(e){console.error(e);res.status(500).json({error:'Server error'});}});
app.get('/api/jobs/:id',async(req,res)=>{try{const r=await pool.query('SELECT * FROM jobs WHERE id=$1',[req.params.id]);if(!r.rows.length)return res.status(404).json({error:'Job not found'});res.json(r.rows[0]);}catch(e){console.error(e);res.status(500).json({error:'Server error'});}});

app.post('/api/apply',async(req,res)=>{
  const b=req.body||{},job_id=Number(b.job_id),full_name=clean(b.full_name),email=clean(b.email)?.toLowerCase(),phone=clean(b.phone),qualification=clean(b.qualification);
  if(!Number.isInteger(job_id)||job_id<1||!full_name||!email)return res.status(400).json({error:'job_id, full_name and email are required'});
  if(!/^\S+@\S+\.\S+$/.test(email))return res.status(400).json({error:'Invalid email address'});
  if(phone&&!/^(?:\+254|254|0)7\d{8}$/.test(phone.replace(/\s+/g,'')))return res.status(400).json({error:'Invalid phone number'});
  const c=await pool.connect();
  try{await c.query('BEGIN');
    if(!(await c.query("SELECT id FROM jobs WHERE id=$1 AND status='Open'",[job_id])).rows.length){await c.query('ROLLBACK');return res.status(404).json({error:'Job not found or closed'});}
    const cr=await c.query(`INSERT INTO candidates(full_name,email,phone,resume_link,cover_letter,source,county,qualification,experience,motivation,cv_file_path) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(email) DO UPDATE SET full_name=EXCLUDED.full_name,phone=EXCLUDED.phone,resume_link=EXCLUDED.resume_link,cover_letter=EXCLUDED.cover_letter,source=EXCLUDED.source,county=EXCLUDED.county,qualification=EXCLUDED.qualification,experience=EXCLUDED.experience,motivation=EXCLUDED.motivation,cv_file_path=EXCLUDED.cv_file_path RETURNING id`,[full_name,email,phone||null,clean(b.resume_link)||null,clean(b.cover_letter)||null,clean(b.source)||null,clean(b.county)||null,qualification||null,clean(b.experience)||null,clean(b.motivation)||null,clean(b.cv_file_path)||null]);
    const ex=await c.query('SELECT * FROM applications WHERE job_id=$1 AND candidate_id=$2 LIMIT 1',[job_id,cr.rows[0].id]);
    if(ex.rows.length){await c.query('ROLLBACK');return res.status(409).json({error:'Application already exists',data:ex.rows[0],lookup_code:ex.rows[0].lookup_code});}
    const a=await c.query(`INSERT INTO applications(job_id,candidate_id,lookup_code,current_stage,payment_status,onboarding_status) VALUES($1,$2,$3,'Applied','Pending','Not Started') RETURNING *`,[job_id,cr.rows[0].id,newLookupCode()]);
    await recordStage(c,a.rows[0].id,null,'Applied','Application submitted');await c.query('COMMIT');res.status(201).json({message:'Application submitted successfully!',data:a.rows[0],lookup_code:a.rows[0].lookup_code});
  }catch(e){await c.query('ROLLBACK');console.error(e);res.status(500).json({error:'Failed to submit application'});}finally{c.release();}
});

app.get('/api/applications',async(req,res)=>{try{res.json((await pool.query(`SELECT a.*,j.title job_title,c.full_name,c.email,c.phone,c.county,c.qualification,c.experience,c.identity_verified,COALESCE((SELECT p.payment_status FROM payments p WHERE p.application_id=a.id ORDER BY p.transaction_date DESC,p.id DESC LIMIT 1),a.payment_status) latest_payment_status,COALESCE((SELECT SUM(p.amount) FROM payments p WHERE p.application_id=a.id AND p.payment_status IN ('Paid','Completed')),0) paid_amount,(SELECT p.mpesa_receipt_number FROM payments p WHERE p.application_id=a.id AND p.payment_status IN ('Paid','Completed') ORDER BY p.transaction_date DESC,p.id DESC LIMIT 1) mpesa_receipt_number,(SELECT i.scheduled_time FROM interviews i WHERE i.application_id=a.id ORDER BY i.scheduled_time DESC,i.id DESC LIMIT 1) last_interview FROM applications a JOIN jobs j ON a.job_id=j.id JOIN candidates c ON a.candidate_id=c.id ORDER BY a.applied_date DESC`)).rows);}catch(e){console.error(e);res.status(500).json({error:'Server error'});}});

app.get('/api/lookup/:code',async(req,res)=>{const code=clean(req.params.code);if(!code)return res.status(400).json({error:'Application code is required'});try{const r=await pool.query(`SELECT a.id,a.lookup_code,j.title job_title,a.current_stage,a.payment_status,a.onboarding_status,c.full_name,c.email,c.phone,c.county,c.qualification,c.experience,c.motivation,c.identity_verified,a.applied_date,a.appointment_date,a.appointment_instructions,a.screening_score,a.screening_decision,a.screening_notes,a.interview_score,a.interview_decision,(SELECT i.id FROM interviews i WHERE i.application_id=a.id ORDER BY i.scheduled_time DESC,i.id DESC LIMIT 1) interview_id,(SELECT i.scheduled_time FROM interviews i WHERE i.application_id=a.id ORDER BY i.scheduled_time DESC,i.id DESC LIMIT 1) interview_time,(SELECT i.status FROM interviews i WHERE i.application_id=a.id ORDER BY i.scheduled_time DESC,i.id DESC LIMIT 1) interview_status,(SELECT i.interviewer_name FROM interviews i WHERE i.application_id=a.id ORDER BY i.scheduled_time DESC,i.id DESC LIMIT 1) interviewer_name,(SELECT i.interview_type FROM interviews i WHERE i.application_id=a.id ORDER BY i.scheduled_time DESC,i.id DESC LIMIT 1) interview_type,(SELECT p.mpesa_receipt_number FROM payments p WHERE p.application_id=a.id AND p.payment_status IN ('Paid','Completed') ORDER BY p.transaction_date DESC,p.id DESC LIMIT 1) mpesa_receipt_number,COALESCE((SELECT SUM(p.amount) FROM payments p WHERE p.application_id=a.id AND p.payment_status IN ('Paid','Completed')),0) paid_amount FROM applications a JOIN jobs j ON j.id=a.job_id JOIN candidates c ON c.id=a.candidate_id WHERE a.lookup_code=$1`,[code]);if(!r.rows.length)return res.status(404).json({error:'Application not found'});const a=r.rows[0];let costs=[];if(['Offer','Hired','Onboarding','Completed'].includes(a.current_stage)){costs=(await pool.query(`SELECT id,COALESCE(item_name,cost_item) item_name,estimated_cost,is_required,payment_status,actual_cost FROM onboarding_costs WHERE application_id=$1 ORDER BY id`,[a.id])).rows;}const next_action=nextStep(a.current_stage);const data_payload={screening_questions:['Applied','Screening'].includes(a.current_stage)?screeningQuestions():[],screening:{score:a.screening_score,decision:a.screening_decision,notes:a.screening_notes},interview:{id:a.interview_id,scheduled_time:a.interview_time,status:a.interview_status,interviewer_name:a.interviewer_name,interview_type:a.interview_type,instructions:a.appointment_instructions},cost_items:costs,payment:{status:a.payment_status,paid_amount:Number(a.paid_amount||0),receipt:a.mpesa_receipt_number}};res.json({...a,stage:a.current_stage,next_step:next_action,next_action,data_payload,is_complete:a.current_stage==='Completed'||a.payment_status==='Paid'});}catch(e){console.error(e);res.status(500).json({error:'Server error'});}});
app.get('/portal/:code',(req,res)=>res.sendFile(path.join(__dirname,'../frontend/portal.html')));

async function handleStageUpdate(req,res,by='HR'){
  const stage=req.body?.stage;if(!ALLOWED_STAGES.has(stage))return res.status(400).json({error:'Invalid stage'});const c=await pool.connect();
  try{await c.query('BEGIN');const ar=await c.query(`SELECT a.*,c.qualification FROM applications a JOIN candidates c ON c.id=a.candidate_id WHERE a.id=$1 FOR UPDATE`,[req.params.id]);if(!ar.rows.length){await c.query('ROLLBACK');return res.status(404).json({error:'Application not found'});}
    if(stage==='Interview'&&!clean(ar.rows[0].qualification)){await c.query('ROLLBACK');return res.status(400).json({error:'Missing required field: qualification'});}
    const t=await transition(c,req.params.id,stage,'Manual stage update',by);if(t.error){await c.query('ROLLBACK');return res.status(400).json({error:`Invalid transition from ${t.previousStage} to ${stage}`});}
    if(stage==='Offer'||stage==='Onboarding')await ensureOnboardingCosts(c,req.params.id);if(stage==='Onboarding')await c.query("UPDATE applications SET onboarding_status='In Progress' WHERE id=$1",[req.params.id]);if(stage==='Completed')await c.query("UPDATE applications SET onboarding_status='Completed' WHERE id=$1",[req.params.id]);
    const r=await c.query('SELECT * FROM applications WHERE id=$1',[req.params.id]);await c.query('COMMIT');res.json(r.rows[0]);
  }catch(e){await c.query('ROLLBACK');console.error(e);res.status(500).json({error:'Server error'});}finally{c.release();}
}
app.patch('/api/applications/:id/stage',handleStageUpdate);
app.patch('/api/applications/:id/status',async(req,res)=>{const map={Pending:'Applied',Reviewed:'Screening',Interview:'Interview',Rejected:'Rejected',Hired:'Hired'},stage=map[req.body?.status];if(!stage)return res.status(400).json({error:'Invalid status'});req.body.stage=stage;return handleStageUpdate(req,res,'HR-Legacy');});
app.post('/api/applications/:id/screening',async(req,res)=>{const decision=req.body?.decision,score=num(req.body?.score),notes=clean(req.body?.notes)||null;if(!['Pass','Fail','Pending'].includes(decision))return res.status(400).json({error:'Invalid screening decision'});if(score!==null&&(!Number.isFinite(score)||score<0||score>100))return res.status(400).json({error:'Screening score must be between 0 and 100'});const c=await pool.connect();try{await c.query('BEGIN');const a=await c.query('SELECT current_stage FROM applications WHERE id=$1 FOR UPDATE',[req.params.id]);if(!a.rows.length){await c.query('ROLLBACK');return res.status(404).json({error:'Application not found'});}const from=a.rows[0].current_stage;if(!['Applied','Screening'].includes(from)){await c.query('ROLLBACK');return res.status(400).json({error:'Application is not available for screening'});}if(from==='Applied'){const t=await transition(c,req.params.id,'Screening','Screening started','HR');if(t.error)throw new Error(t.error);}await c.query('UPDATE applications SET screening_score=$1,screening_decision=$2::text,screening_notes=$3 WHERE id=$4',[score,decision,notes,req.params.id]);if(decision==='Pass'||decision==='Fail'){const t=await transition(c,req.params.id,decision==='Pass'?'Interview':'Rejected',`Screening decision: ${decision}`,'HR');if(t.error)throw new Error(t.error);}const r=await c.query('SELECT * FROM applications WHERE id=$1',[req.params.id]);await c.query('COMMIT');res.json(r.rows[0]);}catch(e){await c.query('ROLLBACK');console.error(e);res.status(500).json({error:'Failed to save screening'});}finally{c.release();}});
app.post('/api/interviews',async(req,res)=>{const b=req.body||{},application_id=Number(b.application_id),scheduled_time=b.scheduled_time,duration=Math.max(15,Number(b.duration_minutes)||60),when=new Date(scheduled_time);if(!Number.isInteger(application_id)||!scheduled_time)return res.status(400).json({error:'application_id and scheduled_time are required'});if(Number.isNaN(when.getTime()))return res.status(400).json({error:'Invalid scheduled_time'});const c=await pool.connect();try{await c.query('BEGIN');const a=await c.query('SELECT current_stage FROM applications WHERE id=$1 FOR UPDATE',[application_id]);if(!a.rows.length){await c.query('ROLLBACK');return res.status(404).json({error:'Application not found'});}if(a.rows[0].current_stage!=='Interview'){await c.query('ROLLBACK');return res.status(400).json({error:'Application must reach Interview stage before scheduling'});}const interviewer=clean(b.interviewer_name)||null;const conflict=await c.query(`SELECT id FROM interviews WHERE status IN ('Scheduled','Confirmed') AND interviewer_name IS NOT DISTINCT FROM $1 AND scheduled_time < ($2::timestamptz + ($3::double precision * INTERVAL '1 minute')) AND (scheduled_time + (COALESCE(duration_minutes,60)::double precision * INTERVAL '1 minute')) > $2::timestamptz LIMIT 1`,[interviewer,when.toISOString(),duration]);if(conflict.rows.length){await c.query('ROLLBACK');return res.status(409).json({error:'Interviewer already has an interview during this time'});}const expiry=new Date(when.getTime()+24*60*60*1000).toISOString();const r=await c.query(`INSERT INTO interviews(application_id,interviewer_name,interview_type,scheduled_time,duration_minutes,meeting_link,status,expiry_time) VALUES($1,$2,$3,$4,$5,$6,'Scheduled',$7) RETURNING *`,[application_id,interviewer,clean(b.interview_type)||'In-person',when.toISOString(),duration,clean(b.meeting_link)||null,expiry]);await c.query('UPDATE applications SET appointment_date=$1,appointment_instructions=$2 WHERE id=$3',[when.toISOString(),clean(b.appointment_instructions)||clean(b.meeting_link)||'Please attend at the scheduled time.',application_id]);await c.query('COMMIT');res.status(201).json(r.rows[0]);}catch(e){await c.query('ROLLBACK');console.error(e);res.status(500).json({error:'Failed to schedule interview'});}finally{c.release();}});
app.post('/api/interviews/:id/confirm',async(req,res)=>{try{const r=await pool.query("UPDATE interviews SET status='Confirmed' WHERE id=$1 AND status='Scheduled' RETURNING *",[req.params.id]);if(!r.rows.length)return res.status(404).json({error:'Interview not found or already confirmed'});res.json(r.rows[0]);}catch(e){console.error(e);res.status(500).json({error:'Failed to confirm interview'});}});
app.post('/api/interviews/:id/score',async(req,res)=>{const decision=req.body?.decision,score=num(req.body?.score);if(!['Hired','Rejected','Hold'].includes(decision))return res.status(400).json({error:'Invalid interview decision'});if(score!==null&&(!Number.isFinite(score)||score<0||score>100))return res.status(400).json({error:'Interview score must be between 0 and 100'});const c=await pool.connect();try{await c.query('BEGIN');const i=await c.query('SELECT * FROM interviews WHERE id=$1 FOR UPDATE',[req.params.id]);if(!i.rows.length){await c.query('ROLLBACK');return res.status(404).json({error:'Interview not found'});}const a=await c.query('SELECT current_stage FROM applications WHERE id=$1 FOR UPDATE',[i.rows[0].application_id]);if(!a.rows.length){await c.query('ROLLBACK');return res.status(404).json({error:'Application not found'});}if(a.rows[0].current_stage!=='Interview'){await c.query('ROLLBACK');return res.status(400).json({error:'Application is not in Interview stage'});}await c.query("UPDATE interviews SET score=$1,feedback=$2,status='Completed' WHERE id=$3",[score,clean(req.body?.feedback)||null,req.params.id]);await c.query('UPDATE applications SET interview_score=$1,interview_decision=$2 WHERE id=$3',[score,decision,i.rows[0].application_id]);if(decision==='Hired'){const t=await transition(c,i.rows[0].application_id,'Offer','Interview decision: Hired','HR');if(t.error)throw new Error(t.error);await ensureOnboardingCosts(c,i.rows[0].application_id);}if(decision==='Rejected'){const t=await transition(c,i.rows[0].application_id,'Rejected','Interview decision: Rejected','HR');if(t.error)throw new Error(t.error);}const r=await c.query('SELECT * FROM interviews WHERE id=$1',[req.params.id]);await c.query('COMMIT');res.json(r.rows[0]);}catch(e){await c.query('ROLLBACK');console.error(e);res.status(500).json({error:'Failed to save interview score'});}finally{c.release();}});
app.get('/api/applications/:id/interviews',async(req,res)=>{try{res.json((await pool.query('SELECT * FROM interviews WHERE application_id=$1 ORDER BY scheduled_time DESC',[req.params.id])).rows);}catch(e){console.error(e);res.status(500).json({error:'Server error'});}});
app.get('/api/applications/:id/stages',async(req,res)=>{try{res.json((await pool.query('SELECT * FROM stage_history WHERE application_id=$1 ORDER BY COALESCE(completed_at,created_at) DESC,id DESC',[req.params.id])).rows);}catch(e){console.error(e);res.status(500).json({error:'Server error'});}});
app.get('/api/applications/:id/progress',async(req,res)=>{try{const a=(await pool.query(`SELECT a.id,a.lookup_code,a.current_stage,a.payment_status,a.onboarding_status,a.applied_date,c.full_name,c.email,j.title job_title FROM applications a JOIN candidates c ON c.id=a.candidate_id JOIN jobs j ON j.id=a.job_id WHERE a.id=$1`,[req.params.id])).rows[0];if(!a)return res.status(404).json({error:'Application not found'});const [st,iv,pay]=await Promise.all([pool.query(`SELECT id,stage_name,status,previous_stage,triggered_by,reason,COALESCE(completed_at,created_at) event_time FROM stage_history WHERE application_id=$1`,[req.params.id]),pool.query(`SELECT id,scheduled_time AS event_time,interview_type,status FROM interviews WHERE application_id=$1`,[req.params.id]),pool.query(`SELECT id,transaction_type,amount,currency,payment_status,transaction_date AS event_time,mpesa_receipt_number,checkout_request_id FROM payments WHERE application_id=$1`,[req.params.id])]);const events=[...st.rows.map(x=>({type:'stage',event_id:`stage-${x.id}`,stage:x.stage_name,status:x.status,previous_stage:x.previous_stage,reason:x.reason,timestamp:x.event_time})),...iv.rows.map(x=>({type:'interview',event_id:`interview-${x.id}`,stage:'Interview',status:x.status,interview_type:x.interview_type,scheduled_time:x.event_time,timestamp:x.event_time})),...pay.rows.map(x=>({type:'payment',event_id:`payment-${x.id}`,stage:'Payment',status:x.payment_status,payment_status:x.payment_status,amount:Number(x.amount),currency:x.currency,receipt:x.mpesa_receipt_number,checkout_request_id:x.checkout_request_id,timestamp:x.event_time}))].sort((x,y)=>new Date(x.timestamp)-new Date(y.timestamp));res.json(events);}catch(e){console.error(e);res.status(500).json({error:'Failed to load application progress'});}});
app.get('/api/onboarding/:id/costs',async(req,res)=>{try{await ensureOnboardingCosts(pool,req.params.id);res.json((await pool.query(`SELECT id,application_id,COALESCE(item_name,cost_item) item_name,cost_item,estimated_cost,actual_cost,is_required,payment_status,incurred_date FROM onboarding_costs WHERE application_id=$1 ORDER BY id`,[req.params.id])).rows);}catch(e){console.error(e);res.status(500).json({error:'Failed to load onboarding costs'});}});
app.get('/api/onboarding/:id',async(req,res)=>{try{await ensureOnboardingCosts(pool,req.params.id);res.json((await pool.query('SELECT * FROM onboarding_costs WHERE application_id=$1 ORDER BY id',[req.params.id])).rows);}catch(e){console.error(e);res.status(500).json({error:'Failed to load onboarding costs'});}});
app.patch('/api/onboarding/:itemId',async(req,res)=>{const actual=req.body?.actual_cost==null?null:Number(req.body.actual_cost),status=clean(req.body?.payment_status);if(actual!==null&&(!Number.isFinite(actual)||actual<0))return res.status(400).json({error:'Invalid actual_cost'});if(status&&!['Unpaid','Paid','Partial'].includes(status))return res.status(400).json({error:'Invalid payment_status'});try{const r=await pool.query(`UPDATE onboarding_costs SET actual_cost=COALESCE($1,actual_cost),payment_status=COALESCE($2,payment_status) WHERE id=$3 RETURNING *`,[actual,status||null,req.params.itemId]);if(!r.rows.length)return res.status(404).json({error:'Cost item not found'});res.json(r.rows[0]);}catch(e){console.error(e);res.status(500).json({error:'Failed to update onboarding cost'});}});
app.patch('/api/candidates/:id/verify',async(req,res)=>{try{const verified=req.body?.identity_verified!==false,notes=clean(req.body?.verification_notes)||null;const r=await pool.query('UPDATE candidates SET identity_verified=$1,verification_notes=$2 WHERE id=$3 RETURNING id,full_name,email,identity_verified,verification_notes',[verified,notes,req.params.id]);if(!r.rows.length)return res.status(404).json({error:'Candidate not found'});res.json(r.rows[0]);}catch(e){console.error(e);res.status(500).json({error:'Failed to update identity verification'});}});
app.post('/api/communications/send',async(req,res)=>{const applicationId=Number(req.body?.application_id),channel=clean(req.body?.channel)||'Email',subject=clean(req.body?.subject)||'',body=clean(req.body?.body)||'';if(!Number.isInteger(applicationId)||!body)return res.status(400).json({error:'application_id and body are required'});if(!['Email','SMS'].includes(channel))return res.status(400).json({error:'Invalid channel'});try{const r=await pool.query('SELECT c.email,c.phone FROM applications a JOIN candidates c ON c.id=a.candidate_id WHERE a.id=$1',[applicationId]);if(!r.rows.length)return res.status(404).json({error:'Application not found'});const recipient=channel==='SMS'?r.rows[0].phone:r.rows[0].email;res.status(201).json(await sendCommunication(applicationId,channel,subject,body,recipient));}catch(e){console.error(e);res.status(500).json({error:'Failed to send communication'});}});
app.post('/api/send-email',async(req,res)=>{const applicationId=Number(req.body?.application_id),subject=clean(req.body?.subject)||'',body=clean(req.body?.body)||'';if(!Number.isInteger(applicationId)||!body)return res.status(400).json({error:'application_id and body are required'});try{const r=await pool.query('SELECT c.email FROM applications a JOIN candidates c ON c.id=a.candidate_id WHERE a.id=$1',[applicationId]);if(!r.rows.length)return res.status(404).json({error:'Application not found'});res.status(201).json(await sendCommunication(applicationId,'Email',subject,body,r.rows[0].email));}catch(e){console.error(e);res.status(500).json({error:'Failed to send email'});}});
app.get('/api/mpesa/status',async(req,res)=>{const checkout=clean(req.query?.checkoutRequestID);if(!checkout)return res.status(400).json({error:'checkoutRequestID is required'});try{const r=await pool.query('SELECT * FROM payments WHERE checkout_request_id=$1',[checkout]);if(!r.rows.length)return res.status(404).json({error:'Payment not found'});res.json(r.rows[0]);}catch(e){console.error(e);res.status(500).json({error:'Server error'});}});
app.post('/api/pay/mpesa',async(req,res)=>{const applicationId=Number(req.body?.application_id),phone=clean(req.body?.phone),amount=Number(req.body?.amount);if(!Number.isInteger(applicationId)||!phone||!Number.isFinite(amount)||amount<=0)return res.status(400).json({error:'application_id, phone and positive amount are required'});if(process.env.MPESA_TEST_MODE==='true'){const checkout=`TEST-${Date.now()}-${Math.floor(Math.random()*1000)}`;const r=await pool.query(`INSERT INTO payments(application_id,transaction_type,amount,currency,mpesa_phone,payment_status,checkout_request_id) VALUES($1,'Onboarding', $2,'KES',$3,'Pending',$4) RETURNING *`,[applicationId,amount,phone,checkout]);res.status(201).json({message:'Test payment initiated',checkoutRequestID:checkout,payment:r.rows[0]});return;}try{const key=process.env.MPESA_CONSUMER_KEY||process.env.MPESA_KEY,secret=process.env.MPESA_CONSUMER_SECRET||process.env.MPESA_SECRET,shortcode=process.env.MPESA_SHORTCODE,passkey=process.env.MPESA_PASSKEY,callback=process.env.MPESA_CALLBACK_URL;if(!key||!secret||!shortcode||!passkey||!callback)return res.status(500).json({error:'M-PESA configuration is incomplete'});const auth=Buffer.from(`${key}:${secret}`).toString('base64');const token=(await axios.get('https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials',{headers:{Authorization:`Basic ${auth}`}})).data.access_token;const timestamp=new Date().toISOString().replace(/[-:TZ.]/g,'').slice(0,14),password=Buffer.from(`${shortcode}${passkey}${timestamp}`).toString('base64'),response=(await axios.post('https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest',{BusinessShortCode:shortcode,Password:password,Timestamp:timestamp,TransactionType:'CustomerPayBillOnline',Amount:Math.round(amount),PartyA:phone.startsWith('254')?phone:`254${phone.slice(-9)}`,PartyB:shortcode,PhoneNumber:phone.startsWith('254')?phone:`254${phone.slice(-9)}`,CallBackURL:callback,AccountReference:`QM-${applicationId}`,TransactionDesc:'QuickMart onboarding payment'},{headers:{Authorization:`Bearer ${token}`}})).data;await pool.query(`INSERT INTO payments(application_id,transaction_type,amount,currency,mpesa_phone,payment_status,merchant_request_id,checkout_request_id,result_code,result_description,callback_payload) VALUES($1,'Onboarding',$2,'KES',$3,'Pending',$4,$5,$6,$7,$8)`,[applicationId,amount,phone,response.MerchantRequestID||null,response.CheckoutRequestID||null,response.ResponseCode?Number(response.ResponseCode):null,response.ResponseDescription||null,response]);res.status(201).json(response);}catch(e){console.error(e.response?.data||e);res.status(502).json({error:'M-PESA request failed',details:e.response?.data||e.message});}});
app.post('/api/mpesa/callback',async(req,res)=>{const cb=req.body?.Body?.stkCallback||req.body?.stkCallback;if(!cb)return res.status(400).json({error:'Invalid callback payload'});const checkout=cb.CheckoutRequestID,resultCode=Number(cb.ResultCode);if(!checkout)return res.status(400).json({error:'Missing CheckoutRequestID'});const items=cb.CallbackMetadata?.Item||[],get=n=>items.find(x=>x.Name===n)?.Value??null,receipt=get('MpesaReceiptNumber'),phone=get('PhoneNumber'),amount=get('Amount');const c=await pool.connect();try{await c.query('BEGIN');const p=await c.query('SELECT * FROM payments WHERE checkout_request_id=$1 FOR UPDATE',[checkout]);if(!p.rows.length){await c.query('ROLLBACK');return res.status(404).json({error:'Payment not found'});}const row=p.rows[0];if(['Paid','Completed'].includes(row.payment_status)){await c.query('COMMIT');return res.json({ResultCode:0,ResultDesc:'Already processed'});}const paid=resultCode===0;await c.query(`UPDATE payments SET payment_status=$1,mpesa_receipt_number=COALESCE($2,mpesa_receipt_number),mpesa_phone=COALESCE($3,mpesa_phone),result_code=$4,result_description=$5,callback_payload=$6,transaction_date=NOW() WHERE id=$7`,[paid?'Paid':'Failed',receipt,phone,resultCode,cb.ResultDesc||null,cb,row.id]);if(paid){const a=await c.query('SELECT current_stage FROM applications WHERE id=$1 FOR UPDATE',[row.application_id]);if(a.rows.length){const stage=a.rows[0].current_stage;if(stage==='Hired'){await transition(c,row.application_id,'Onboarding','M-PESA payment completed','M-PESA');await c.query("UPDATE applications SET onboarding_status='In Progress',payment_status='Paid' WHERE id=$1",[row.application_id]);}else{await c.query("UPDATE applications SET payment_status='Paid' WHERE id=$1",[row.application_id]);}}}else await c.query("UPDATE applications SET payment_status='Failed' WHERE id=$1",[row.application_id]);await c.query('COMMIT');res.json({ResultCode:0,ResultDesc:'Accepted'});}catch(e){await c.query('ROLLBACK');console.error(e);res.status(500).json({error:'Failed to process callback'});}finally{c.release();}});
app.post('/api/paystack/webhook',async(req,res)=>{try{const data=req.body?.data;if(data?.reference){const applicationId=Number(data.metadata?.application_id||data.metadata?.applicationId);if(Number.isInteger(applicationId)){await pool.query(`INSERT INTO payments(application_id,transaction_type,amount,currency,payment_status,metadata) VALUES($1,'Onboarding',$2,$3,$4,$5)`,[applicationId,Number(data.amount||0)/100,data.currency||'KES',data.status==='success'?'Paid':'Failed',data]);if(data.status==='success')await pool.query("UPDATE applications SET payment_status='Paid' WHERE id=$1",[applicationId]);}}res.json({received:true});}catch(e){console.error(e);res.status(500).json({error:'Webhook processing failed'});}});
app.get('/api/dashboard/stats',async(req,res)=>{try{const [total,stages,pending,interviewsToday]=await Promise.all([pool.query('SELECT COUNT(*)::int total_applications FROM applications'),pool.query('SELECT current_stage,COUNT(*)::int count FROM applications GROUP BY current_stage ORDER BY current_stage'),pool.query("SELECT COALESCE(SUM(amount),0)::numeric pending_amount,COUNT(*)::int pending_payments FROM payments WHERE payment_status='Pending'"),pool.query("SELECT COUNT(*)::int interviews_today FROM interviews WHERE scheduled_time::date=CURRENT_DATE AND status IN ('Scheduled','Confirmed')")]);res.json({total_applications:total.rows[0].total_applications,by_stage:stages.rows,pending_payments:pending.rows[0],interviews_today:interviewsToday.rows[0].interviews_today});}catch(e){console.error(e);res.status(500).json({error:'Server error'});}});
app.get('/api/dashboard/queue',async(req,res)=>{const stage=clean(req.query?.stage);try{const params=[];let where='';if(stage){if(!ALLOWED_STAGES.has(stage))return res.status(400).json({error:'Invalid stage'});params.push(stage);where='WHERE a.current_stage=$1';}const r=await pool.query(`SELECT a.id,a.lookup_code,a.current_stage,a.applied_date,c.full_name,c.email,c.phone,j.title job_title FROM applications a JOIN candidates c ON c.id=a.candidate_id JOIN jobs j ON j.id=a.job_id ${where} ORDER BY a.applied_date DESC`,params);res.json(r.rows);}catch(e){console.error(e);res.status(500).json({error:'Server error'});}});

app.get('/health',(req,res)=>res.json({ok:true}));
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:'Unexpected server error'});});
app.listen(PORT,()=>console.log(`QuickMart server listening on ${PORT}`));
