import { db, storage } from "hatchable";
import { sendRecruitmentEmail } from "lib/recruitment-mail.js";
export const access = "public";
export const methods = ["GET", "POST"];
const refPattern=/^QM-APP-[A-Z0-9]{10}$/;
const screeningQuestions=["How old are you?","What is your current highest education level?","What certificate or qualification do you hold? If none, select None.","How many years of relevant work experience do you have?","Which QuickMart position are you applying for, and which county would you prefer to work in?","Are you available to work shifts, weekends and public holidays when the role requires it?"];
const interviewQuestions=["Tell us briefly about yourself and the experience or skills that make you suitable for this role.","Why are you interested in this position, and what would you like to contribute to the team?","Tell us about a time you helped a customer, colleague, or another person solve a problem. What did you do?","How would you handle an angry or dissatisfied customer while remaining professional?","Imagine the branch is very busy and several customers need help at the same time. How would you prioritise your work?","Tell us about a time you worked as part of a team. What was your contribution?","What would you do if you made a mistake at work or noticed a mistake made by a colleague?","When would you be available to start work, and are you comfortable working shifts when the role requires it?"];
function cleanRef(v){return String(v||"").trim().toUpperCase();}
function publicStage(a){return {application_ref:a.application_ref,full_name:a.full_name,email:a.email,phone:a.phone,home_county:a.home_county,preferred_branch_county:a.preferred_branch_county,applied_position:a.applied_position,recruitment_stage:a.recruitment_stage,screening_decision:a.screening_decision,interview_date:a.interview_date,interview_time:a.interview_time,interview_invited_at:a.interview_invited_at,interview_expires_at:a.interview_expires_at,interview_submitted:!!a.interview_submitted_at,payment_status:a.payment_status,total_amount_kes:a.total_amount_kes,selected_cost_item_ids:a.selected_cost_item_ids,appointment_date:a.appointment_date,appointment_time:a.appointment_time,appointment_instructions:a.appointment_instructions};}
async function loadApplicant(ref){const {rows}=await db.query("SELECT id,application_ref,full_name,email,phone,home_county,preferred_branch_county,applied_position,recruitment_stage,screening_decision,interview_date,interview_time,interview_invited_at,interview_expires_at,interview_answers,interview_submitted_at,payment_status,total_amount_kes,selected_cost_item_ids,appointment_date,appointment_time,appointment_instructions,national_id FROM applicants WHERE application_ref=$1 LIMIT 1",[ref]);return rows[0];}
export default async function(req,res){
 const body=typeof req.body==="string"?JSON.parse(req.body||"{}"):req.body||{};const ref=cleanRef(req.method==="GET"?req.query?.ref:body?.applicationRef);if(!refPattern.test(ref))return res.status(400).json({success:false,message:"A valid QuickMart application reference is required."});const applicant=await loadApplicant(ref);if(!applicant)return res.status(404).json({success:false,message:"This recruitment link is no longer active. Please contact the recruitment team."});
 if(req.method==="GET"){
  const stage=String(applicant.recruitment_stage||"application_received");const expires=applicant.interview_expires_at?new Date(applicant.interview_expires_at):null;const windowOpen=!!applicant.interview_invited_at&&!!expires&&expires.getTime()>Date.now();let next="screening_wait";
  if(stage==="application_received")next="screening";
  else if(stage==="screening")next="screening_wait";
  else if((stage==="shortlisted"||stage==="interview")&&windowOpen)next="interview";
  else if((stage==="shortlisted"||stage==="interview")&&applicant.interview_invited_at)next="interview_expired";
  else if(stage==="interview_submitted")next="interview_wait";
  else if(stage==="selected")next="careers";
  else if(stage==="onboarding")next="onboarding";
  else if(stage==="completed"||String(applicant.payment_status||"").toLowerCase()==="paid")next="completed";
  else if(stage==="rejected")next="rejected";
  let positions=[];let costs=[];
  if(next==="careers"||next==="onboarding"){positions=(await db.query("SELECT title,monthly_pay_kes,slots_available FROM position_catalog WHERE active=true AND slots_available>0 ORDER BY title")).rows;costs=(await db.query("SELECT id,name,description,price_kes,is_required FROM cost_items WHERE active=true ORDER BY is_required DESC,created_at")).rows;}
  return res.json({success:true,stage:next,applicant:publicStage(applicant),screening_questions:stage==="screening"?screeningQuestions:[],questions:next==="interview"?interviewQuestions:[],positions,costs});
 }
 if(body.mode==="update_costs"){
  if(!['onboarding'].includes(String(applicant.recruitment_stage)))return res.status(403).json({success:false,message:"Onboarding payment options are not available at this stage."});
  const {rows:activeCosts}=await db.query("SELECT id,price_kes,is_required FROM cost_items WHERE active=true ORDER BY created_at");
  const requested=new Set(Array.isArray(body.selectedCostItemIds)?body.selectedCostItemIds.map(String):[]);
  const selected=activeCosts.filter(c=>c.is_required||requested.has(String(c.id)));const ids=selected.map(c=>String(c.id));const total=selected.reduce((s,c)=>s+Number(c.price_kes||0),0);
  const {rows:updated}=await db.query("UPDATE applicants SET selected_cost_item_ids=$2::jsonb,total_amount_kes=$3 WHERE id=$1 AND recruitment_stage='onboarding' RETURNING application_ref,total_amount_kes,selected_cost_item_ids",[applicant.id,JSON.stringify(ids),total]);
  return res.json({success:true,applicant:updated[0],selected_costs:selected,total_amount_kes:total});
 }
 if(body.mode==="onboarding_apply"){
  if(String(applicant.recruitment_stage)!=="selected")return res.status(403).json({success:false,message:"The final Apply section becomes available only after HR approves the interview."});
  const nationalId=String(body.nationalId||"").trim(),phone=String(body.phone||"").trim().replace(/[\s-]/g,""),position=String(body.appliedPosition||"").trim();
  if(!/^\d{7,9}$/.test(nationalId))return res.status(400).json({success:false,message:"Enter a valid Kenyan National ID number (7–9 digits)."});
  if(!/^254(?:7|1)\d{8}$/.test(phone))return res.status(400).json({success:false,message:"Enter a valid Kenyan mobile number in 254 format."});
  const {rows:pos}=await db.query("SELECT title,monthly_pay_kes,slots_available FROM position_catalog WHERE title=$1 AND active=true LIMIT 1",[position]);if(!pos.length||Number(pos[0].slots_available)<=0)return res.status(409).json({success:false,message:"That position is no longer available. Choose another open position."});
  const {rows:activeCosts}=await db.query("SELECT id,price_kes,is_required,name FROM cost_items WHERE active=true ORDER BY created_at");const optionalIds=new Set(Array.isArray(body.selectedCostItemIds)?body.selectedCostItemIds.map(String):[]);const selected=activeCosts.filter(c=>c.is_required||optionalIds.has(String(c.id)));const selectedIds=selected.map(c=>String(c.id));const total=selected.reduce((s,c)=>s+Number(c.price_kes||0),0);
  const {rows:updated}=await db.query("UPDATE applicants SET national_id=$2,phone=$3,applied_position=$4,selected_cost_item_ids=$5::jsonb,total_amount_kes=$6,recruitment_stage='onboarding' WHERE id=$1 AND recruitment_stage='selected' RETURNING application_ref,full_name,email,phone,applied_position,total_amount_kes,recruitment_stage",[applicant.id,nationalId,phone,position,JSON.stringify(selectedIds),total]);if(!updated.length)return res.status(409).json({success:false,message:"This application has already moved to another stage. Reopen the same recruitment portal link."});
  try{await sendRecruitmentEmail({applicant:updated[0],type:"onboarding"});}catch(err){console.warn("QuickMart onboarding email unavailable:",String(err?.message||err));}
  return res.json({success:true,message:"Final Apply details saved. Continue to secure Paystack checkout when ready.",applicant:updated[0],selected_costs:selected});
 }
 const stage=String(applicant.recruitment_stage||"");const expires=applicant.interview_expires_at?new Date(applicant.interview_expires_at):null;if(!['shortlisted','interview'].includes(stage)||!applicant.interview_invited_at||!applicant.interview_expires_at||expires.getTime()<=Date.now())return res.status(403).json({success:false,message:"The interview is not currently available for this application."});
 const nationalId=String(body.nationalId||"").trim();if(!/^\d{7,9}$/.test(nationalId))return res.status(400).json({success:false,message:"Enter a valid Kenyan National ID number (7–9 digits)."});if(applicant.national_id&&String(applicant.national_id)!==nationalId)return res.status(403).json({success:false,message:"The National ID does not match the ID already attached to this application."});
 let parsed=null;if(body.answersJson){try{parsed=JSON.parse(String(body.answersJson));}catch{return res.status(400).json({success:false,message:"Interview answers could not be read."});} }const answers=(parsed&&typeof parsed==='object'&&!Array.isArray(parsed))?parsed:body.answers;if(!answers||typeof answers!=='object'||Array.isArray(answers))return res.status(400).json({success:false,message:"Please complete the interview questions."});const clean={};for(let i=0;i<interviewQuestions.length;i++){const v=String(answers[String(i)]??"").trim();if(v.length<10)return res.status(400).json({success:false,message:`Please answer interview question ${i+1} with at least 10 characters.`});clean[String(i)]=v.slice(0,2000);}
 const cvFile=Array.isArray(req.files)?req.files.find(f=>String(f.field||"")==="cv"):null;if(!cvFile||!cvFile.buffer||!cvFile.filename)return res.status(400).json({success:false,message:"Please attach your CV as a PDF, DOC, or DOCX file (maximum 5 MB)."});const filename=String(cvFile.filename).replace(/[^a-zA-Z0-9._-]/g,"_").slice(-120),lower=filename.toLowerCase();const types=new Set(["application/pdf","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document"]);if(!types.has(String(cvFile.contentType||""))&&!/[.](?:pdf|doc|docx)$/.test(lower))return res.status(400).json({success:false,message:"CV must be a PDF, DOC, or DOCX file."});if(Number(cvFile.buffer.length||0)>5*1024*1024)return res.status(400).json({success:false,message:"CV file must be 5 MB or smaller."});const cvUrl=await storage.put(`recruitment-cv/${applicant.id}/${crypto.randomUUID()}-${filename}`,cvFile.buffer,String(cvFile.contentType||"application/octet-stream"));const {rows:updated}=await db.query("UPDATE applicants SET national_id=$2,cv_url=$3,cv_filename=$4,interview_answers=$5::jsonb,interview_submitted_at=now(),recruitment_stage='interview_submitted' WHERE id=$1 RETURNING application_ref,full_name,email,applied_position,recruitment_stage,interview_submitted_at",[applicant.id,nationalId,cvUrl,filename,JSON.stringify(clean)]);try{await sendRecruitmentEmail({applicant:updated[0],type:"interview_received"});}catch(err){console.warn("QuickMart interview email unavailable:",String(err?.message||err));}return res.json({success:true,message:"Interview submitted successfully. The recruitment team will now review your interview.",applicant:updated[0]});
}